# Generated by Django 5.2.3 on 2025-06-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_cover_image_alter_option_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
    ]
