# Generated by Django 5.2.3 on 2025-06-24 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_quiz_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="questions_per_attempt",
            field=models.PositiveSmallIntegerField(
                default=15,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
    ]
