# Generated by Django 5.2.3 on 2025-06-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_result_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeredquestion",
            name="selected_option",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="quiz.option"
            ),
        ),
    ]
